### DISCUSSION TITLE
Adding new user via cloud-init

### DISCUSSION THREAD

**Discussion by dkirrane** [vmware/packer-examples-for-vsphere#299] [Help] [answered]
Trying to add a new user via cloud-init but the user is not getting created.

I'm using the [Terraform cloud-init example](https://github.com/vmware-samples/packer-examples-for-vsphere/blob/main/terraform/vsphere-virtual-machine/template-linux-cloud-init/main.tf)

I've updated the [userdata.yml](https://github.com/vmware-samples/packer-examples-for-vsphere/blob/main/terraform/vsphere-virtual-machine/template-linux-cloud-init/userdata.yml) to add a new user

```
---
users:
  - name: foo
    gecos: Foo B. Bar
    primary_group: foobar
    groups: adm
    sudo: true
    shell: /bin/bash
    lock_passwd: false
    passwd: $6$j212wezy$7H/1LT4f9/N3wpgNunhsIqtMj62OKiS3nyNwuizouQc3u7MbYCarYeAHWYPYb2FT.lbioDm2RrkJPb9BZMN1O/
```

After I create the vm via terraform I ssh to it but the user is not listed:
`cut -d: -f1 /etc/passwd`
