### DISCUSSION TITLE
Is there any reason build.sh can't be replaced with an Ansible playbook?

### DISCUSSION THREAD

**Discussion by bschonec** [vmware/packer-examples-for-vsphere#516] [Ideas]
### Code of Conduct

- [X] I have read and agree to the project's Code of Conduct.

### Description

Is there any reason that the ./build.sh BASH script couldn't be replaced by an Ansible playbook?  A lot of duplication could be eliminated by converting the script to an ansible playbook using loops and includes.  Each [menu option](https://github.com/vmware-samples/packer-examples-for-vsphere/blob/main/build.sh#L22) would be a task or two [tagged](https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_tags.html) for the operating system intended to be built.

### Use Case(s)

As Ansible is one of the most-used configuration management tools, I'm sure there would be a large pool of people who could contribute.  I have much more skill in Ansible than in BASH (in fact, I rarely use BASH scripts any more) and the ansible toolset is more powerful.

### Potential Configuration

ansible-playbook build.yml --tags=debian_11,centos9_stream

### References

#394

[a comment by an automated account is not shown]

**Comment by bschonec** [comment]
Here is some very crude pseudo-code.  I realize that there are probably mistakes in the code itself but I think it's enough to get my point across on the feature upgrade I'm suggesting:

```
---

- name: Build a VMware template
  gather_facts: false
  become: false
  hosts: localhost
  vars:
    host_list:
      rocky9:
        input_path: "{{ script_path }}/builds/linux/rocky/9/"
    vars_files:
      - vsphere.pkrvars.hcl
      - build.pkrvars.hcl
      - ansible.pkrvars.hcl
      - proxy.pkrvars.hcl
      - common.pkrvars.hcl
    
  tasks:

  # Here we append each member of the var_files list into a packer_build_args variable via a loop.
  - name: Build the Packer command line:
    set_fact:
      packer_build_args: "{{ packer_build_args | default('') + '-var-file=\"' + item }} + ' '"
    loop: "{{ vars_files }}" 

  - name: "Initialize Packer."
    shell: "packer init {{ host_list[desired_host]['input_path']}" 

  - name: "Build a {{ desired_host }} host."
    shell: "packer build --force {{ host_list[desired_host]['input_path'}}" 

ansible-playbook -i localhost, build_vmware_image.yml -e 'desired_host=rocky_9'

```
