### DISCUSSION TITLE
Packer Gitlab CI/CD pipelines

### DISCUSSION THREAD

**Discussion by dvm191** [vmware/packer-examples-for-vsphere#654] [Help] [answered]
Hey, was wondering if you worked on a gitlab pipeline to create the templates?

trying to re-work some of the code to make it work and running into a few walls. so thought i would ask.

Thanks,

**Comment by tenthirtyam** [comment]
No, not at this time.

**Comment by rcroft-work** [comment, marked as answer]
I have got something working for our internal gitlab setup. 

Couple of things to note:
- I trigger builds manually when I update ISO files/checksum
- Below works for me and promises/commitments that it works for your env.

Tried to stay inline the gomplate model used for `build.sh` so created a `build-ci.tmpl`

```
##############################################################################
##
## CI/CD for building OVFs in the packer content library on Common Pool
##
##############################################################################

default:
    image: "harbor.sydeng.vmware.com/library/packerplus:dev"

variables:
    SCRIPT_PATH: "${CI_PROJECT_DIR}"
    CONFIG_PATH: "${CI_PROJECT_DIR}/config"
    INPUT_PATH: ""
    EXTRA_VAR_FILES: ""
    BUILD_ONLY: ""

##############################################################################

.packer-build:
    stage: build
    tags: 
        - container
    before_script:
        - "packer init \"$INPUT_PATH\""
#        - "packer validate \"$INPUT_PATH\""
    script:
        - "packer build -force -on-error=ask -var-file=\"$CONFIG_PATH/vsphere.pkrvars.hcl\" -var-file=\"$CONFIG_PATH/build.pkrvars.hcl\" -var-file=\"$CONFIG_PATH/ansible.pkrvars.hcl\" -var-file=\"$CONFIG_PATH/proxy.pkrvars.hcl\" -var-file=\"$CONFIG_PATH/common.pkrvars.hcl\" ${EXTRA_VAR_FILES} ${BUILD_ONLY} \"$INPUT_PATH\""
    when: manual

##############################################################################

{{ range $menu := (ds "build").menu -}}
{{ range $submenu := $menu.submenu -}}

{{ $submenu.entry | strings.ReplaceAll " (cloud-init)" "" | strings.ReplaceAll " " "-" | strings.ReplaceAll "---" "-" }}:
    extends: .packer-build
    variables:
        INPUT_PATH: "$SCRIPT_PATH/{{ $submenu.build.path }}"
{{- if (coll.Has $submenu.build "only") }}
        BUILD_ONLY: "--only {{ join $submenu.build.only "," }}"
{{- end -}}
{{- if (coll.Has $submenu.build "var_files") -}}
{{ range $submenu.build.var_files }}
        EXTRA_VAR_FILES: " -var-file=$CONFIG_PATH/{{ . }}"
{{- end -}}{{- end }}

##############################################################################

{{ end }}{{ end -}}
```

I run the following command line to build the `.gitlab-ci.yml` from the `build-ci.tmpl` above and the `build.yml`:

```
gomplate -c build.yaml -f build-ci.tmpl -o .gitlab-ci.yml
```

There are no changes to the `build.yaml`.
